# Generated by Django 2.2.4 on 2021-01-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examuser',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
