# Generated by Django 2.2.4 on 2021-01-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210121_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='img',
            field=models.URLField(default='https://www.classfly.in/static/4.png'),
        ),
    ]
