# Generated by Django 2.2.4 on 2021-01-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_examsubject_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='sn',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='toc',
            field=models.URLField(default=''),
        ),
    ]
