# Generated by Django 2.2.4 on 2021-01-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20210121_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='examuser',
            name='started',
            field=models.DateTimeField(null=True),
        ),
    ]
