# Generated by Django 2.2.4 on 2021-01-23 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_examuser_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.CharField(max_length=20)),
                ('type', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('exam_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certfct', to='exam.ExamUser')),
            ],
        ),
    ]
