# Generated by Django 2.2.4 on 2021-02-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
