# This example uses pyjwt:
# pip install pyjwt

import jwt
import base64
import time


playback_id = 'sEdW9ii8KvJdjzfeS3KAnCr1yskVLsTrOcWzIomcnWk' # enter your playback id here
signing_key_id = 'gsAx1ozB1fM802wSzUpVQEad8fKfW2z5QRioIJXPPyQ4' # enter your signing key id here
private_key_base64 = 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbGlrY0VpVy9NYXppWkNMbzFmOFdKSXptK05DSHhDUE5abzRpclNYWms0WmY1RlFuClJGOHhzTVdBaThUUnFEYXJSZnFEQnNFNXcrNlRvemdUdUtQY0pRdEpzZ0VKVkhPeldrcEN1VjB1cy9FUldLRUMKU245SW5PMmZNQUh1b2xPY0diM3l0V1BNN3h5Wmx6SjZ1d2JvYlMzTFE1bFIzOWlSQXFST1lOSzR5Q2xUV2dOUwpLV2h4NE9qK2dqTVpxTlN1c0xCQ21VVHlqdmxZa1ZIRmhaRXN5TFlUR0dIaS9jMmpTNEFZS2ZhaHpTZjl2bVorClozcTdIZEk3OWNESmdnak8zYlZMTFlhb1RXZXB1dFpUSXdTZjhEWGdHQUNxOHpMajI4Nm5nc2xUcXRSNys1TmkKa1VJNmtxeDlKejVFVXJDeDZZa1hiQkpTMUIzVEdRbkp2OVJSclFJREFRQUJBb0lCQUJadmpnSW9JYWtLYThrSwpiaitMSFlQWWlhb2pmaVdRTStCZTNFK0NtRCt5bENGSmNaU0ZwS2NFMjNBR3VFeXAzbTFXUUwyQm9WL2xCYW9kCmR0VGZwc1RpS3VDdHh2Y1hVblRySTQwT255dkRtUlBrK3JLbTBmS2dqbWhkNFluZmRETmtiaDhzQ2pLdjAwTUUKQjlKcDlkQmFSMFNTWStsT01seHlzRU5IT05TdkhXdFpNcmJyVkg3MnRsdnNuc2FzeFlOWUhGdzNIclZDUHBlWgp5eWNWUm5uM0JKZlR6dW9KOFpDcE9Pei8zMFhDc3oxWnJOTFp3Tm5VOTZmemlSOHlFa0pzMUl4bURIMlkyYmcyCkNXV0t3d3VWc3F2ZVVXWnFxek5OdnJ1VUlybzlMUlVIMXNxcERyL1hxWWFTdXJ2bmU5WHptSzZBWFptQ1RsN1oKYmd0TlZ3RUNnWUVBd0VtMUo2SEpjLzZvMDJnU1J5ckZGakwxNzBhb2Vwc2ZjQW9KbHJOSllqNktoeDBUOGFtcQpnMFN5eTVYV0RZMDlXVHQwTk9pbHc2dk5tT3hlallKZWduNDduQlMxSGlkSFhSTG51WHVMWS9rVDBXWWZQcFhxCkwxNFJwUng5VDBDTlg4UmNBQ0dyazVuOFI0TENQektmWUZ0cmlyalArWm1KcVR6bno5S042cHNDZ1lFQXgrb1IKSlJhN0kwTUEzYVhEUXUzZEZMa3dTME1MQ0Z4bXhtT0IxaDVtWkJOd0w1RkJONmpTRnZjSzlQMjZNV0lxYUVaZgpuYW9weU91WGErYktYUGtaSENhY09Ib0JhVzBZL3o0YnZCSUlFWTBUQzA2M3FpWXJ6TTQ4aWE5c3NHRVQ0dG5PCmdCSGtvT0h1dGJCTGRvVTlDYXlxalh0amZ3azR4Sm5XV0ZiT3RWY0NnWUFjdWlaTlVIZG5VL0ZtL0JKVy9ZWEsKUmp6RnpabVlENXJIdzBnaGNwR1JFdVRoUUsvZEY4cjRwNGZLc0l6MUkxZTZBQTdoWkt4M0tqQ2lHeFlaTUJQcwpqTzFjNlI4UjdTNVZNbURhTGlIcUFxazZUSFo0aEM4amVudEtYcEkrQjlmWEtkL1F5VGIzNnpac2ZKV0dtWXFECis4UjZTaGdRSXljVTJKdU5TZGlYNXdLQmdCUzRyVWhEMytmYXhSYzBYRlh1bzlESEZUdG4ycGZtUS96aVNZM3gKSHJuV3pmVVFRRXRObzJFZ0FERytydkw1Y3QzV0ZZa1pIeldsUGMvQVgwOWR2bjJOZnZuWG81ZlM2QmxremFragowVlJJWkNYeTVkU3NHalFqV0dFSkh1SDFYZ05RZ2pnQ0lzbU9RWmp4aWhEaDVKN0JGL2lNUnBiZlZOUUVBaFNzCkFzY0hBb0dCQUxWdkg2by9ncXZsd2VlbzExZlJmeWl5MGZnaEpzSEVKcGZZUTZOQVErdlkvRFNDeWc2VzVycHYKcFBSWk50c3NtVDQ4Nnd1UlpsQlBTNmtNYmxma1NLUWc4c3ZEbCtqRC9FdC9HUDRRcnVwbzRNNEJkbnpRRlhCeQo0amEyRFBUUVUzZ29jb3JuU3BsZURpOXFIUXBPOEsrM0VPYkpxdng4SjBOS0tLR1FFOGhiCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==' # enter your base64 encoded private key here
 
private_key = base64.b64decode(private_key_base64)

token = {
    'sub': playback_id,
    'exp': int(time.time()) + 3600, # 1 hour
    'aud': 'v'
}

headers = {
    'kid': signing_key_id
}

json_web_token = jwt.encode(
    token, private_key, algorithm="RS256", headers=headers)

# You need to decode the token, otherwise you'll get a `b'` at the start of the string.
print(json_web_token)

# import requests
# requests.get("http://sms.textmysms.com/app/smsapi/index.php?key=35FD9ADAC248D5&campaign=0&routeid=13&type=text&contacts={}&senderid=SOFTEC&msg=Welcome+to+ClassFly%2C+Your+password:{}%2CLogin+with+this+password.".format('6295705310','classfly@123'))


