# Generated by Django 2.2.4 on 2021-06-10 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=70)),
                ('designation', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('stream', models.CharField(max_length=60)),
                ('college', models.CharField(max_length=80)),
                ('language_spoke', models.CharField(max_length=150)),
                ('about_yourself', models.TextField(max_length=500)),
                ('total_exp_year', models.FloatField()),
                ('resume_url', models.URLField()),
                ('profile_pic', models.URLField()),
                ('skills', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proaccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=80)),
                ('designation', models.CharField(max_length=80)),
                ('project', models.CharField(max_length=60)),
                ('cfrom', models.CharField(max_length=20)),
                ('cto', models.CharField(max_length=20)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='interview.Prfessional')),
            ],
        ),
    ]
