# Generated by Django 2.2.4 on 2021-06-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_prfessional_proexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional_Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet1', models.DateTimeField()),
                ('meet2', models.DateTimeField()),
                ('meet3', models.DateTimeField()),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='interview.Prfessional')),
            ],
        ),
    ]
