# Generated by Django 2.2.4 on 2021-06-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_remove_hraccount_office_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hraccount',
            name='idcard',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='hraccount',
            name='profilepic',
            field=models.URLField(default=''),
        ),
    ]
