# Generated by Django 2.2.4 on 2021-06-19 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0006_auto_20210618_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
    ]
