# Generated by Django 2.2.4 on 2021-06-19 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0008_auto_20210619_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=200)),
                ('resume', models.URLField()),
                ('company', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('experience', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('profile_pic', models.URLField()),
                ('interviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_interviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
