# Generated by Django 2.2.4 on 2021-06-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default='new', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProfessionalTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_timings', to='interview.Prfessional')),
            ],
        ),
        migrations.CreateModel(
            name='Professinal_Interview_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet', models.CharField(max_length=3)),
                ('time', models.TimeField()),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_interview', to='interview.Prfessional')),
            ],
        ),
        migrations.CreateModel(
            name='Professinal_Account_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=11)),
                ('account_number', models.CharField(max_length=18)),
                ('name', models.CharField(max_length=40)),
                ('upi', models.CharField(max_length=40)),
                ('pro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_bank_account', to='interview.Prfessional')),
            ],
        ),
    ]
