# Generated by Django 2.2.4 on 2021-06-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_auto_20210628_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='hraccount',
            name='office_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hraccount',
            name='designation',
            field=models.CharField(max_length=50),
        ),
    ]
