# Generated by Django 2.2.4 on 2021-06-29 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_auto_20210628_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_on', models.DateTimeField()),
                ('interview_url', models.URLField()),
                ('topics', models.CharField(max_length=300)),
                ('comments', models.CharField(max_length=200)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewed', to='interview.Expert')),
                ('pro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_interview', to='interview.Prfessional')),
            ],
        ),
    ]
