# Generated by Django 2.2.4 on 2021-07-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0012_professionalinterview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfessionalTimeTable',
        ),
    ]
