# Generated by Django 2.2.8 on 2021-07-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0014_fresher_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresher',
            name='profile_pic',
            field=models.URLField(default=''),
        ),
    ]
