# Generated by Django 2.2.8 on 2021-08-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0015_auto_20210716_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about',
            field=models.TextField(default='', max_length=800),
        ),
    ]
