# Generated by Django 2.2.8 on 2021-08-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0016_company_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='exp_company',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='experience',
            name='exp_period',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='experience',
            name='exp_work',
            field=models.CharField(default='', max_length=500),
        ),
    ]
