# Generated by Django 2.2.8 on 2021-08-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0017_auto_20210814_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresher',
            name='city',
            field=models.CharField(default='Bangalore', max_length=50),
        ),
    ]
