# Generated by Django 2.2.8 on 2021-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0018_fresher_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalinterview',
            name='interview_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
