# Generated by Django 2.2.8 on 2021-08-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0019_auto_20210820_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresher',
            name='language_spoken',
            field=models.CharField(default='', max_length=100),
        ),
    ]
