# Generated by Django 2.2.8 on 2021-08-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0020_fresher_language_spoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresher',
            name='master_branch',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='fresher',
            name='master_college',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fresher',
            name='pre_branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fresher',
            name='pre_college',
            field=models.CharField(default='', max_length=50),
        ),
    ]
