# Generated by Django 2.2.8 on 2021-08-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0021_auto_20210821_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresher',
            name='master_passout',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='fresher',
            name='pre_passout',
            field=models.IntegerField(default=2000),
        ),
    ]
