# Generated by Django 2.2.8 on 2021-08-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0022_auto_20210821_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresher',
            name='master_passout',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='fresher',
            name='passout_year',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='fresher',
            name='pre_passout',
            field=models.IntegerField(default=None),
        ),
    ]
