# Generated by Django 2.2.8 on 2021-08-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0023_auto_20210825_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fresher',
            name='master_passout',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fresher',
            name='passout_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fresher',
            name='pre_passout',
            field=models.IntegerField(default=0),
        ),
    ]
