# Generated by Django 2.2.8 on 2021-08-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0024_auto_20210825_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='fresher',
            name='city_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fresher',
            name='city_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fresher',
            name='city_3',
            field=models.CharField(default='', max_length=50),
        ),
    ]
