# Generated by Django 2.2.8 on 2021-09-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0025_auto_20210830_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfessional',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prfessional',
            name='meeting_time_updated',
            field=models.BooleanField(default=False),
        ),
    ]
