# Generated by Django 2.2.8 on 2021-11-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0026_auto_20210921_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proexperience',
            name='project',
            field=models.CharField(max_length=500),
        ),
    ]
