# Generated by Django 2.2.8 on 2021-09-14 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fresher', '0005_profrehsermeeting_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingUid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_uid', models.IntegerField(default=0)),
                ('fresh_uid', models.IntegerField(default=0)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uids', to='fresher.ProFrehserMeeting')),
            ],
        ),
    ]
