# Generated by Django 2.2.8 on 2021-10-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordinguid',
            name='record_uid',
            field=models.IntegerField(default=0),
        ),
    ]
