# Generated by Django 2.2.8 on 2021-08-07 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview', '0015_auto_20210716_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=60)),
                ('skills', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=800)),
                ('requirement', models.TextField(max_length=800)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('min_salary', models.FloatField()),
                ('max_salary', models.FloatField()),
                ('min_exp', models.FloatField()),
                ('max_exp', models.FloatField()),
                ('qu1', models.CharField(max_length=400)),
                ('qu2', models.CharField(max_length=400)),
                ('qu3', models.CharField(max_length=400)),
                ('active', models.BooleanField(default=False)),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posted', to='interview.HRaccount')),
            ],
        ),
    ]
