# Generated by Django 2.2.8 on 2021-08-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervideo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='employment_type',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='functional_area',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='industry_type',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='role',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='role_category',
            field=models.CharField(default='', max_length=60),
        ),
    ]
