# Generated by Django 2.2.8 on 2021-08-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervideo', '0002_auto_20210807_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='edu_doc',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='edu_pg',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='edu_ug',
            field=models.CharField(default='', max_length=60),
        ),
    ]
