# Generated by Django 2.2.8 on 2021-08-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervideo', '0003_auto_20210807_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='functional_area',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='role_category',
        ),
    ]
