# Generated by Django 2.2.8 on 2021-08-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0016_company_about'),
        ('intervideo', '0004_auto_20210807_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicantion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('ans1', models.TextField(max_length=800)),
                ('ans2', models.TextField(max_length=800)),
                ('ans3', models.TextField(max_length=800)),
                ('fresher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_applied', to='interview.Fresher')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='intervideo.Jobpost')),
            ],
        ),
    ]
