# Generated by Django 2.2.8 on 2021-08-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervideo', '0005_applicantion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
