# Generated by Django 2.2.8 on 2021-08-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervideo', '0006_jobpost_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantion',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantion',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
