# Generated by Django 2.2.8 on 2021-08-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervideo', '0007_auto_20210811_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantion',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
