# Generated by Django 2.2.8 on 2021-08-14 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0017_auto_20210814_2008'),
        ('intervideo', '0008_auto_20210811_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='FresherInvited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('fresher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_to', to='interview.Fresher')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to='intervideo.Jobpost')),
            ],
        ),
    ]
