# Generated by Django 2.2.8 on 2021-08-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervideo', '0009_fresherinvited'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
