# Generated by Django 2.2.8 on 2021-08-26 07:46

from django.db import migrations, models
import intervideo.models


class Migration(migrations.Migration):

    dependencies = [
        ('intervideo', '0010_jobpost_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='deleted_date',
            field=models.DateTimeField(default=intervideo.models.now),
        ),
    ]
