# Generated by Django 2.2.8 on 2021-09-01 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0005_profrehsermeeting_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intervideo', '0011_jobpost_deleted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_views', to='fresher.ProFrehserMeeting')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default='', max_length=50)),
                ('pro_designation', models.CharField(default='', max_length=50)),
                ('skills', models.CharField(default='', max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_queries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
