# Generated by Django 2.2.8 on 2021-09-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervideo', '0012_interviewsearch_interviewvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewvideo',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
