# Generated by Django 2.2.8 on 2021-09-01 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intervideo', '0013_interviewvideo_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewvideo',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='interviewvideo',
            name='like',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.RemoveField(
            model_name='interviewvideo',
            name='user',
        ),
        migrations.AddField(
            model_name='interviewvideo',
            name='user',
            field=models.ManyToManyField(related_name='user_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
