# Generated by Django 2.2.8 on 2021-09-01 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import intervideo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intervideo', '0014_auto_20210901_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewvideo',
            name='user',
        ),
        migrations.AddField(
            model_name='interviewvideo',
            name='user',
            field=models.ForeignKey(default=intervideo.models.defaultUser, on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
