# Generated by Django 2.2.8 on 2021-09-03 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intervideo', '0015_auto_20210901_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.CharField(max_length=10)),
                ('service', models.CharField(default='', max_length=80)),
                ('amount', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('service_type', models.CharField(default='', max_length=20)),
                ('razor_order_id', models.CharField(max_length=30)),
                ('razorpay_payment_id', models.CharField(default='', max_length=20)),
                ('razorpay_signature', models.CharField(default='', max_length=70)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_done', to='intervideo.Payment')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_purchase', to='intervideo.InterviewVideo')),
            ],
        ),
    ]
