# Generated by Django 2.2.8 on 2021-09-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0005_profrehsermeeting_designation'),
        ('intervideo', '0016_payment_videopurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='razor_order_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='MeetingPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repaid', models.BooleanField(default=False)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_purchase', to='fresher.ProFrehserMeeting')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_meeting', to='intervideo.Payment')),
            ],
        ),
    ]
