# Generated by Django 2.2.8 on 2021-09-04 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intervideo', '0017_auto_20210904_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.IntegerField(default=0)),
                ('skills_count', models.IntegerField(default=0)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_payment_done', to='intervideo.Payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_purchase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
