# Generated by Django 2.2.8 on 2021-09-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervideo', '0018_resumepurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.CharField(default='', max_length=20),
        ),
    ]
