# Generated by Django 2.2.4 on 2021-02-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_number',
            name='filename',
            field=models.CharField(default='', max_length=50),
        ),
    ]
