# Generated by Django 2.0 on 2020-08-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
