# Generated by Django 2.2.8 on 2021-07-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview', '0013_delete_professionaltimetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProFrehserMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(null=True)),
                ('date_time', models.DateTimeField()),
                ('skills', models.CharField(max_length=500)),
                ('paid', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('channel_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('mode', models.CharField(max_length=3)),
                ('feedback', models.TextField(default='', max_length=1000)),
                ('passed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('fresher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fresher_interview', to='interview.Fresher')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews_done', to='interview.Prfessional')),
            ],
        ),
    ]
