# Generated by Django 2.2.8 on 2021-07-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_joined', models.BooleanField(default=False)),
                ('fre_joined', models.BooleanField(default=False)),
                ('record_started', models.BooleanField(default=False)),
                ('record_stopped', models.BooleanField(default=False)),
                ('uploaded_vdo', models.BooleanField(default=False)),
                ('resource_id', models.CharField(max_length=600, null=True)),
                ('sid', models.CharField(max_length=600, null=True)),
                ('vdo_id', models.CharField(max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('record_start_time', models.DateTimeField(null=True)),
                ('record_stop_time', models.DateTimeField(null=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_details', to='fresher.ProFrehserMeeting')),
            ],
        ),
    ]
