# Generated by Django 2.2.8 on 2021-07-28 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0002_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.IntegerField(default=0)),
                ('fres', models.IntegerField(default=0)),
                ('record', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_status', to='fresher.ProFrehserMeeting')),
            ],
        ),
    ]
