# Generated by Django 2.2.8 on 2021-08-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0003_meetingactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='profrehsermeeting',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
