# Generated by Django 2.2.8 on 2021-08-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0004_profrehsermeeting_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='profrehsermeeting',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
