# Generated by Django 2.2.4 on 2020-11-23 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DeptHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_depthead', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chapter', models.IntegerField(default=1)),
                ('cf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoDeptHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=20)),
                ('report_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_head_report_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dept_head', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('usn', models.CharField(max_length=20)),
                ('dept_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_to_dept_head', to='video.VideoDeptHead')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_maker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideosMade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail_link', models.CharField(max_length=600)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('report', models.TextField(default='', max_length=1000)),
                ('status', models.BooleanField(null=True)),
                ('video_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_made', to='video.VideoMaker')),
            ],
        ),
        migrations.CreateModel(
            name='VideoId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('title', models.CharField(default='', max_length=200)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_videos', to='video.Playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descp', models.CharField(default='', max_length=200)),
                ('imgurl', models.URLField(default='https://www.classfly.in/static/assets/img/comm.jpg')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_subjects', to='video.Department')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_playlist', to='video.Subject'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depthead_playlist', to='video.DeptHead'),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chapter', models.IntegerField(default=1)),
                ('note_link', models.CharField(max_length=300)),
                ('active', models.BooleanField(null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('report', models.CharField(default='', max_length=500)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_noteslist', to='video.Subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_uploaded', to='video.VideoMaker')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='video.EducationDomain'),
        ),
    ]
