# Generated by Django 2.2.4 on 2020-11-23 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_department_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chapter', models.IntegerField(default=1)),
                ('note_link', models.CharField(max_length=300)),
                ('active', models.BooleanField(null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('report', models.CharField(default='', max_length=500)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_bookslist', to='video.Subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_uploaded', to='video.VideoMaker')),
            ],
        ),
    ]
