# Generated by Django 2.2.4 on 2020-09-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='chapter',
            field=models.IntegerField(default=1),
        ),
    ]
