# Generated by Django 2.2.4 on 2020-09-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_playlist_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cf',
            field=models.BooleanField(default=False),
        ),
    ]
