# Generated by Django 2.2.4 on 2020-09-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_playlist_cf'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoid',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
