# Generated by Django 2.2.4 on 2020-10-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_videoid_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='descp',
            field=models.CharField(default='', max_length=200),
        ),
    ]
