# Generated by Django 2.2.4 on 2020-10-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_subject_descp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='imgurl',
            field=models.URLField(default='https://www.classfly.in/static/assets/img/comm.jpg'),
        ),
    ]
