# Generated by Django 2.2.4 on 2020-10-01 04:53

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('video', '0007_subject_imgurl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domain',
            new_name='Department',
        ),
    ]
