# Generated by Django 2.2.4 on 2020-10-01 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_department_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='video.EducationDomain'),
        ),
    ]
