# Generated by Django 2.2.4 on 2020-10-28 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0011_auto_20201001_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDeptHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=20)),
                ('report_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_head_report_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('usn', models.CharField(max_length=20)),
                ('dept_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_to_dept_head', to='video.VideoDeptHead')),
            ],
        ),
        migrations.CreateModel(
            name='VideosMade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail_link', models.CharField(max_length=600)),
                ('video_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_made', to='video.VideoMaker')),
            ],
        ),
    ]
