# Generated by Django 2.2.4 on 2020-10-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_videodepthead_videomaker_videosmade'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosmade',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videosmade',
            name='report',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='videosmade',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
