# Generated by Django 2.2.4 on 2020-10-31 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0013_auto_20201028_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodepthead',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dept_head', to=settings.AUTH_USER_MODEL),
        ),
    ]
