# Generated by Django 2.2.4 on 2020-11-20 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_uploaded', to='video.VideoMaker'),
        ),
    ]
