# Generated by Django 2.2.4 on 2020-11-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_auto_20201120_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
