# Generated by Django 2.2.4 on 2020-11-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0019_notes_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='datetime',
        ),
    ]
