# Generated by Django 2.2.4 on 2020-11-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0020_remove_notes_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
