# Generated by Django 2.2.4 on 2020-11-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0021_notes_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='report',
            field=models.CharField(default='', max_length=500),
        ),
    ]
