# Generated by Django 2.2.8 on 2021-09-06 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(default='', max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('fresher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fre_chat', to=settings.AUTH_USER_MODEL)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=500)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('chatgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chatt.TwoGroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
