# Generated by Django 2.2.8 on 2021-09-15 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0005_profrehsermeeting_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatt', '0002_onlinestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('locked', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_chatt', to='fresher.ProFrehserMeeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('meeting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_chats', to='chatt.MeetingChat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meet_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
