# Generated by Django 2.2.8 on 2021-09-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatt', '0003_meetingchat_meetingmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingchat',
            name='channel_name',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
