# Generated by Django 2.2.8 on 2021-09-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatt', '0004_meetingchat_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='twogroup',
            name='fresher_lastseen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='twogroup',
            name='prof_lastseen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
