# Generated by Django 2.2.8 on 2021-10-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatt', '0005_auto_20210923_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingmessages',
            name='message',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
