# Generated by Django 2.2.8 on 2021-10-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatt', '0006_auto_20211002_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
