# Generated by Django 2.2.8 on 2021-10-02 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatt', '0007_auto_20211002_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twogroup',
            name='fresher_lastseen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='twogroup',
            name='prof_lastseen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
