# Generated by Django 2.2.8 on 2021-10-02 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatt', '0008_auto_20211002_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinestatus',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
