# Generated by Django 2.2.4 on 2021-03-17 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=5000)),
                ('work', models.CharField(max_length=20)),
                ('meetings', models.IntegerField()),
                ('presentation', models.BooleanField(default=False)),
                ('internship', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=500)),
                ('program_flow_dscp', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('exp', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=200)),
                ('playback_id', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_videos', to='pro.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('percent', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='pro.Project')),
            ],
        ),
        migrations.CreateModel(
            name='RegsiteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_key', models.CharField(max_length=300)),
                ('private_key', models.TextField(max_length=3000)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0)),
                ('feedback', models.TextField(max_length=3000, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_users', to='pro.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_registered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow', to='pro.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_subjects', to='pro.Trainer'),
        ),
    ]
