# Generated by Django 2.2.4 on 2021-03-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_length',
            field=models.CharField(default='10', max_length=10),
        ),
    ]
