# Generated by Django 2.2.4 on 2021-03-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_project_video_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regsitereduser',
            name='private_key',
            field=models.TextField(default='null', max_length=3000),
        ),
        migrations.AlterField(
            model_name='regsitereduser',
            name='sign_key',
            field=models.CharField(default='null', max_length=300),
        ),
    ]
